language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit
  - php vendor/kherge/box/bin/box build -c compile.json

after_script:
  - php bin/codacycoverage clover

